name = "TiledIteration"
uuid = "06e1c1a7-607b-532d-9fad-de7d9aa2abac"
author = ["Tim Holy <tim.holy@gmail.com>"]
version = "0.4.1"

[deps]
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
ArrayInterface = "3"
Documenter = "0.27"
OffsetArrays = "0.8, 0.9, 0.10, 0.11, 1"
julia = "1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter", "LoopVectorization"]
