name = "TiledIteration"
uuid = "06e1c1a7-607b-532d-9fad-de7d9aa2abac"
author = ["Tim Holy <tim.holy@gmail.com>"]
version = "0.3.0"

[deps]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
OffsetArrays = "0.8, 0.9, 0.10, 0.11, 1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Test", "Documenter"]
